name: CI/CD Docker Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Jeim

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yt-api:latest
          platforms: linux/arm64

      - name: Deploy to Oracle VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yt-api:latest
            docker stop yt-api || true
            docker rm yt-api || true
            docker run -d --name yt-api --network docker_network-main -p 7777:3001 \
              -e PORT=3001 \
              -e YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/yt-api:latest
